# Generated by Django 3.2.9 on 2021-11-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aysef', '0002_alter_support_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',)},
        ),
    ]
