# Generated by Django 3.2.9 on 2021-11-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysef', '0003_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
