# Generated by Django 3.2.9 on 2021-11-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aysef', '0004_emailmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
